# SPDX-FileCopyrightText: Copyright © 2026 Jarred C. Lloyd
# SPDX-FileContributor: Jarred C. Lloyd <4o8pg2v9h@mozmail.com>
#
# SPDX-License-Identifier: MPL-2.0

# GeochemistryToolsCore.jl/Transformations.jl
# Mathematical Transformations

export pseudolog, invpseudolog, cartesian, ternary

"""
    pseudolog(x::Real, σ::Real=0.05, base::Real=ℯ})

Transform x -> pseudolog(x)

```
julia> pseudolog(1.0)
2.99822295029797
```

# References

Johnson, NL (1949) 'Systems of frequency curves generated by methods of translation', *Biometrika*, 36(1/2):149–176, https://doi.org/10.2307/2332539
"""
function pseudolog(x::Real, σ::Real = 0.05, base::Real = ℯ)
    return asinh(x / (2 * σ) / log(base))
end

"""
    invpseudolog(x::Real, σ::Real=0.05, base::Real=ℯ})

Transform invpseudolog(x) -> x

```
julia> invpseudolog(2.99822295029797)
1.0000000000000002
```
"""
function invpseudolog(x::Real, σ::Real = 0.05, base::Real = ℯ)
    return 2 * σ * sinh(x * log(base))
end


"""
    cartesian(a::Real, b::Real, c::Real)

Transforms ternary coordinates (a, b, c) to Cartesian coordinates (x, y).

# Notes

Will normalise the sum of (a, b, c) to 1 if it is not already ≈ 1.

  - `(1, 0, 0)` corresponds to the apex (x, y = 0.5, √3/2) of the triangle i.e. 100% `a`
  - `(0, 1, 0)` corresponds to the origin (left vertex) (x, y = 0, 0) i.e. 100% `b`
  - `(0, 0, 1)` is the right most vertex (x, y = 1, 0) i.e. 100% `c`

```
julia> cartesian(1, 0, 0)
(0.5, 0.8660254037844386)

```

# References

Shimura, T & Kemp, AIS (2015) 'Tetrahedral plot diagram: A geometrical solution for quaternary systems', *American Mineralogist*, 100(11–12):2545–2547, https://doi.org/10.2138/am-2015-5371
"""
function cartesian(a::Real, b::Real, c::Real)
    if isapprox(+(a, b, c), 1)
        return Tuple([0.5 0 1; √3/2 0 0] * [a, b, c])
    else
        return Tuple([0.5 0 1; √3/2 0 0] * ([a, b, c] ./ +(a, b, c)))
    end
end

"""
    ternary(x::Real, y::Real)

Transforms Cartesian coordinates (x, y) to ternary coordinates (a, b, c).

```
julia> ternary(0,0)
(0.0, 1.0, 0.0)
```

# References

Shimura, T & Kemp, AIS (2015) 'Tetrahedral plot diagram: A geometrical solution for quaternary systems', *American Mineralogist*, 100(11–12):2545–2547, https://doi.org/10.2138/am-2015-5371
"""
function ternary(x::Real, y::Real)
    a, b = inv([[0.5, √3 / 2] .- [1, 0] [0, 0] .- [1, 0]]) * ([x, y] .- [1, 0])
    c = 1 - a - b
    return (a, b, c)
end

"""
    ternary(a::Real, b::Real, c::Real, d::Real)

Transforms tetrahedral coordinates (a, b, c, d) to ternary coordinates (a, b, c).

# Notes

Will normalise the sum of (a, b, c, d) to 1 if it is not already ≈ 1.

  - `(1, 0, 0, 0)` corresponds to the apex of the facing triangle of the tetrahedron, i.e. 100% `a`
  - `(0, 1, 0, 0)` corresponds to the origin (left vertex) of the facing triangle of the tetrahedron, i.e. 100% `b`
  - `(0, 0, 1, 0)` is the right most vertex of the facing triangle, i.e. 100% `c`
  - `(0, 0, 0, 1)` is the rear vertex of the tetrahedron behind the facing triangle, i.e. 100% `d`

```
julia> ternary(0, 0, 1, 0)
(1.0, 0.0, 0.0)
```

# References

Shimura, T & Kemp, AIS (2015) 'Tetrahedral plot diagram: A geometrical solution for quaternary systems', *American Mineralogist*, 100(11–12):2545–2547, https://doi.org/10.2138/am-2015-5371
"""
function ternary(a::Real, b::Real, c::Real, d::Real)
    if isapprox(+(a, b, c, d), 1)
        return Tuple([0.5 0 1 0.5; √3/2 0 0 √3/6; 0 0 0 √6/3] * [a, b, c, d])
    else
        return Tuple([0.5 0 1 0.5; √3/2 0 0 √3/6; 0 0 0 √6/3] *
                     ([a, b, c, d] ./ +(a, b, c, d)),)
    end
end
